language: cpp

cache:
  ccache: true
  timeout: 1000
  directories:
    - keystores

env:
  global:
    - QTVER=5.12.3
    - PPAQTVER=512
    - QTIFWVER=3.1.1
    - APPIMAGEVER=12
    - ARCH_ROOT_DATE=2019.08.01
    - ARCH_ROOT_URL=https://mirror.rackspace.com/archlinux
    - FFMPEG_VERSION=4.2
    - SDKVER=4333796
    - NDKVER=r19c
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
    # BT_KEY
    - secure: "sFnbUeX1mP/G4LVT56VDFyDgWS8KKy7qSlmhNg6YRJuhtfcAoiBjJrO300TREg46nUK3QAwSHt/py3F5WSdHcZ2dniV8ON+zLL0qcVxTglB2DHVUeCStYykTqoV3uZoxYYPHXCd1KTW3ZzdSpCaHVl39REtM0R4tMARNkl3lYhEsS7M6TCjispTLLl9qXdSp86IvtMCPx3mcbjcY59pk/fwwUgneRbocD+7DyVZfFvF98UXh5VGPIKry65DLhNowqsDtBZqYqlAih2LAOuJPxCQKe4pEdPZm81kzGduIV1X+AjBEv7W5K8IXdNm4EG7gMS74i4XW4p4Jn5Axr8An4kTsZnTaGUE0t2RjCJicoa3+CkYJTRDM6CoXoBBJQoerued3MVrH7DvuYtslyrmW4nJu8bTNmVGjS8zuPq4QbfZmekxzbMQWjuEcsw7iwAHIf/hDyRtUUX/T4ioDAU5C72Wx6XSSlSlEDCeEBuM3jnsS5zf54g39mgZkPGlbTaRrdYuxmmDBvh9mYzbb1ANcUW3XEu5rA+j69xOeeVLQVbXZJd04zudBzFg5Kyp2cGNI1KC+27ZOvSTRtrG+V7Ham9lEisJ01tUASV0gdUUSSYHPvD8z6bfJF30Gj/W7hBXqOzXpo2SQ/jPHQ4O68tlUlVBYu2HcCCjHncb25NJWpMk="

matrix:
  include:
  - os: osx
    osx_image: xcode11
    compiler: clang

before_install: |
  if [ -z "${ANDROID_BUILD}" ]; then
    if [ "${TRAVIS_OS_NAME}" = linux ] && [ -z "${ARCH_ROOT_BUILD}" ]; then
      docker pull ${DOCKERIMG}
      docker ps -a
      docker run --privileged -it -d -v ${PWD}:/sources -v $HOME/.ccache:/ccache -e CCACHE_DIR=/ccache -w /sources --name ${DOCKERSYS} ${DOCKERIMG} /bin/sh
    elif [ "${TRAVIS_OS_NAME}" = osx ]; then
      brew unlink python
      brew update
      brew upgrade
      brew link --overwrite numpy
    fi
  fi

install:
  - chmod +x ports/ci/travis/install_deps.sh
  - ports/ci/travis/install_deps.sh

before_script: |
  if [ "${ANDROID_BUILD}" = 1 ]; then
    export COMPILESPEC=android-${COMPILER}
  elif [ "${ARCH_ROOT_BUILD}" = 1 ] && [ ! -z "${ARCH_ROOT_MINGW}" ]; then
    export CXX=${ARCH_ROOT_MINGW}-w64-mingw32-g++
    export COMPILESPEC=win32-g++
  elif [ "${TRAVIS_OS_NAME}" = linux ]; then
    if [ "${CXX}" = g++ ]; then
      export COMPILESPEC=linux-g++
    elif [ "${CXX}" = clang++ ]; then
      export COMPILESPEC=linux-clang
    fi
  elif [ "${TRAVIS_OS_NAME}" = osx ]; then
    brew link --force qt5
    if [ "${CXX}" = g++ ]; then
      export COMPILESPEC=macx-g++
    elif [ "${CXX}" = clang++ ]; then
      export COMPILESPEC=macx-clang
    fi
  fi

script:
  - chmod +x ports/ci/travis/build.sh
  - ports/ci/travis/build.sh

after_success:
  - chmod +x ports/ci/travis/deploy.sh
  - ports/ci/travis/deploy.sh

branches:
  only:
    - zero/autoblur

addons:
  artifacts:
    s3_region: "us-west-2"
    debug: true
    paths:
      - $(ls ./ports/deploy/packages_auto/mac/* | tr "\n" ":")
    working_dir: ports/deploy/packages_auto/mac
